schema_version = "1.0.0"

id = "blender_production_system"
version = "1.1.4"
name = "Blender Production System"
tagline = "Modular character production tools for Blender"
maintainer = "Patrice Newson"
type = "add-on"

website = "https://github.com/SadeJudah/blender-production-system"

tags = [
  "Pipeline",
  "Development",
  "Modeling",
  "Sculpt",
  "User Interface",
]

blender_version_min = "4.2.0"

license = [
  "SPDX:MIT",
]
